### ISSUE TITLE
Replace git update command

### ISSUE THREAD

**Issue by clburlison** [clburlison/profiles#2]
Need to test this on a machine that doesn't have my git config. I think I can replace 

`git pull; git submodule update --init --recursive`

with

`git pull --recurse-submodules`

**Comment by groob** [comment]
Nope, doesn't work. I tried it. 

You need `git submodule update --init --recursive` after you clone. 
It's also possible to clone and download the submodules simultaneously with 
`git clone --recursive`

**Comment by clburlison** [comment]
Awesome. Thanks for testing!

**Comment by clburlison** [comment]
Closing. The current commands are correct.
